name: test yaml file for github actions
on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-lates
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flask

            - name: Run tests
              run: |
                  echo "Running tests..."